---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r lobsterEffort-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r lobsterEffort-load-common-ha, child = here::here("reports/sections/commonSections/commonHA.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { 
  # load in generic data, e.g.functions, study area, and base maps into the 
  # environment, when knitting, these will be loaded through the child rmd.
  lapply(list.files(here::here("app/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment())
  assign("rrEnv", new.env(), envir=globalenv())
  rrEnv$haClassTable <- data.frame(row.names=c("Coastal", "Shoreline", "Offshore"))
}
```

### **Inshore Lobster Landings and Fishing Effort** {#lobsterEffort-section}

```{r lobsterEffort-load, include=FALSE}
# load in section specific data
load_rdata(c("lobsterEffort_rr"), regionStr, env = environment())

```

```{r lobsterEffort-meta, results='asis'}
# metadata blurb at start of each section
write_meta(lobsterEffort_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_lobsterEffort]:
```{r lobsterEffort-text, results='asis'}
writeLines(noquote(lobsterEffort_rr$text$en))

```


##### *Area-Specific Lobster Fishing Effort Results*
```{r lobsterEffort-results, include=FALSE, cache=FALSE}
# clip the data to the Study and Map areas:
lobsterOutputList <- master_intersect(lobsterEffort_rr$data_sf, mapDataList, getRegion=TRUE)

```

```{r lobsterEffort-haTable, echo=FALSE, results='asis'}
if (!is.null(lobsterOutputList$studyData)) {
  rrEnv$haClassTable$`Lobster Effort` <- list("Coastal" = TRUE, 
                                            "Offshore" = FALSE, 
                                            "Shoreline" = TRUE)
}
```

```{r lobsterEffort-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
lobsterEffortReport <- if (is.null(lobsterOutputList$studyData)) {
  "* There are no relevant lobster fishing effort records for this search area."
} else {
  "* There are relevant lobster fishing effort records for this search area."
}
writeLines(noquote(lobsterEffortReport))
```

```{r lobsterEffort-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(lobsterEffort_rr, "EN"), 'Grid map of lobster fishing effort (annual catch weight per number of trap hauls) within the Scotian Shelf bioregion. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Dashed grey lines indicate international boundaries. Data were obtained from @OpenData_lobsterEffort.')}
if (!is.null(lobsterOutputList$studyData)) {
    plot(plot_rr_sf(regionMap, lobsterOutputList$regionData, 
                    attribute=lobsterEffort_rr$attribute, 
                    legendName="Catch weight (kg/yr)", 
                    continuousAttr=TRUE))
  }
```

```{r lobsterEffort-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(lobsterEffort_rr, "EN"), 'Grid map of lobster fishing effort (annual catch weight per number of trap hauls) within the search area (red outline). Data were obtained from @OpenData_lobsterEffort.')}
if (!is.null(lobsterOutputList$studyData)) {
    totalRegionMax <- max(lobsterOutputList$regionData[[lobsterEffort_rr$attribute]])
    totalRegionMin <- min(lobsterOutputList$regionData[[lobsterEffort_rr$attribute]])
    plot(plot_rr_sf(areaMap, lobsterOutputList$mapData, 
                    attribute=lobsterEffort_rr$attribute, 
                    legendName="Catch weight (kg/yr)", 
                    continuousAttr=TRUE, 
                    minScale=totalRegionMin, maxScale=totalRegionMax))}
```


