
---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r child = here::here("sections/commonSections/commonIntro.Rmd")}
if (FALSE) { #load in data:
  lapply(list.files(here::here("app/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```
### **Zones d’importance écologique et biologique (ZIEB)**  

```{r EBSA-load, include=FALSE}
load_rdata(c("ebsa_rr"), regionStr, env = environment())
```

```{r EBSA-meta, results='asis'}
write_meta(ebsa_rr, "FR")
```
Histoir ZIEB: <https://gisp.dfo-mpo.gc.ca/portal/apps/MapJournal/index.html?appid=b91f85de60f44a7b90633e4b43e3916a>

Description de l’ensemble de données (tirée du dossier des données ouvertes)  [@OpenData_ebsa]:
```{r EBSA-text, results='asis'}
writeLines(noquote(ebsa_rr$text$fr))

```

#### ***Résultats de la recherche des ZIEB par zone***  

```{r EBSA-results, echo=FALSE, results='asis'}
#function for overlap
EBSAoutput <- master_intersect(ebsa_rr$data_sf, mapDataList, getRegion=TRUE)
```
 
```{r EBSA-check, echo=FALSE, results='asis'}
#function for overlap
Query_output_EBSA<-if(is.null(EBSAoutput$studyData)){
    "* La zone de recherche ne chevauche pas les zones d’importance écologique et biologique (ZIEB)."
  } else {
    "* La zone de recherche chevauche les zones d’importance écologique et biologique (ZIEB)."
  }
Query_output_EBSA2<-noquote(Query_output_EBSA)

writeLines(Query_output_EBSA)

```

```{r EBSA-table,  echo=FALSE, results='asis'}
EBSATable <- EBSA_report(EBSAoutput$studyData, lang="FR")
if (!is.null(EBSATable)){
   knitr::kable(EBSATable, align="l", caption="Details for EBSA's overlapping the study area.</b>", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```


```{r EBSA-region-plot, fig.height=7, fig.width=11, fig.cap= 'Niveau de qualité : Élevée. Niveau de sécurité : Aucun. Carte montrant les zones d’importance écologique et biologique (ZIEB) par rapport à la zone de recherche définie par l’utilisateur (entourée de rouge).'}
if (!is.null(EBSAoutput$regionData)){
  plot_rr_sf(regionMap, EBSAoutput$regionData, ebsa_rr$attribute)
}
```

```{r EBSA-area-plot, fig.height=7, fig.width=11, fig.cap= 'Niveau de qualité : Élevée. Niveau de sécurité : Aucun. Carte montrant les zones d’importance écologique et biologique (ZIEB) dans la zone de recherche définie par l’utilisateur (entourée de rouge).'}
if(!is.null(EBSAoutput$studyData)){
  plot_rr_sf(areaMap, EBSAoutput$mapData, ebsa_rr$attribute)
}
```
