
---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r oecm-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
``` 

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```
### **Autres mesures de conservation efficaces par zone**  

```{r OECM-load, include=FALSE}
load_rdata(c("oecm_rr"), regionStr, env = environment())
```

```{r OECM-meta, results='asis'}
write_meta(oecm_rr, "FR")
```

Description de l’ensemble de données (tirée du dossier des données ouvertes)  [@OpenData_oecm]:
```{r OECM-text, results='asis'}
writeLines(noquote(oecm_rr$text$fr))

```

#### ***Résultats de la recherche des OECM par zone***  

```{r OECM-results, echo=FALSE, results='asis'}
#function for overlap
OECMoutput <- master_intersect(oecm_rr$data_sf, mapDataList, getRegion=TRUE)
```
 
```{r OECM-check, echo=FALSE, results='asis'}
#function for overlap
Query_output_OECM<-if(is.null(OECMoutput$studyData)){
    "* 
La zone de recherche chevauche les autres mesures de conservation efficaces basées sur la zone (OECM)."
  } else {
    "* 
La zone de recherche ne chevauche pas les autres mesures de conservation efficaces basées sur la zone (OECM)."
  }
Query_output_OECM2<-noquote(Query_output_OECM)

writeLines(Query_output_OECM)

```

```{r OECM-table,  echo=FALSE, results='asis'}
OECMTable <- OECM_report(OECMoutput$studyData, lang="FR")
if (!is.null(OECMTable)){
   knitr::kable(OECMTable, align="l", caption="Détails des OECM chevauchant la zone d'étude</b>", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```


```{r OECM-region-plot, fig.height=7, fig.width=11, fig.cap= 'Carte montrant les autres mesures de conservation efficaces basées sur la zone dans la biorégion du plateau néo-écossais. La zone de recherche est représentée par un contour rouge et une vue plus détaillée est présentée dans la figure ci-dessous, si des données pertinentes sont présentes. Les données ont été obtenues à partir de @OpenData_oecm.'}
if (!is.null(OECMoutput$regionData)){
  plot_rr_sf(regionMap, OECMoutput$regionData, oecm_rr$attribute)
}
```

```{r OECM-area-plot, fig.height=7, fig.width=11, fig.cap= 'Carte montrant les autres mesures de conservation efficaces basées sur la zone dans la zone de recherche (contour rouge). Les données ont été obtenues à partir de @OpenData_oecm.'}
if(!is.null(OECMoutput$studyData)){
  plot_rr_sf(areaMap, OECMoutput$mapData, oecm_rr$attribute)
}
```
