---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r rv-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **Maritimes Research Vessel (RV) Survey**{#RV-section}

```{r rv-load, include=FALSE}
load_rdata(c("rv_rr"), "MAR", env = environment())
```

```{r rv-meta, results='asis'}
write_meta(rv_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_MAR_RV]:
```{r rv-text, results='asis'}
writeLines(noquote(rv_rr$text$en))
```

```{r table-RV-read, echo=FALSE, cache=FALSE, include = FALSE}
table_RV <- read.csv(here::here("app/data/misc/table_RV_EN.csv"))
table_RV <- table_RV %>% dplyr::rename("Season/Months" = Season.Months, "Description of Geographic Range" = Description.of.Geographic.Range)
```

```{r RV-table-setup}
knitr::kable(table_RV, align = "l",
      caption = "Summary of data collected during the 4 distinct Maritimes Research Vessel (RV) Surveys. See @chadwick2007history for more information on the timeline and periodic adjustment of the 4VSW surveys.", booktabs = T, escape = F, linesep = "") %>% kable_styling(bootstrap_options = "striped", full_width = T, position = "left")
```

##### *Area-Specific Maritimes Research Vessel (RV) Survey Search Results*

```{r RV-results, include=FALSE, cache=FALSE}
outputList <- master_intersect(rv_rr$data_sf, mapDataList, Year = minYear)

# summary intro table
introResult <- !is.null(outputList$studyData)
summaryIntroTable <- add_row_to_intro_summary(summaryIntroTable, name="[RV Survey](#RV-section)", result=introResult)


tableList <- create_table_RV(outputList$studyData, listed_species)
rvAllTable <- tableList$allSpecies
rvSarTable <- tableList$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[RV](#RV-section)", rvSarTable, "Common Name", "Individuals")

```

```{r RV-check, comment="", prompt=TRUE, echo=FALSE, results='asis'}
if (is.null(outputList$studyData)) {
    Report_RV <- "* There are no relevant records in the Maritimes Research Vessel (RV) Survey for this search area."
    surveyTypeDf <- NULL
  } else {
    Report_RV <- "* There are relevant records in the Maritimes Research Vessel (RV) Survey for this search area."
    surveyTypeTable <- table(unique(outputList$studyData[,c('ELAT','ELONG','geometry', 'surveyType')])$surveyType)
    surveyTypeDf <- as.data.frame(surveyTypeTable)
    names(surveyTypeDf) <- c("Suvery", "Number of trawl samples")
    rownames(surveyTypeDf) <- NULL
  }
Report_RV<-noquote(Report_RV)
writeLines(Report_RV)

if (!is.null(surveyTypeDf) > 0) {
    knitr::kable(surveyTypeDf, align="l", caption="Breakdown of surveys present in search area.", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
  }


```

```{r RV-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(rv_rr, "EN"), 'Map of the Maritimes Research Vessel (RV) Trawl Survey data in relation to the search area (red outline). Blue lines and arrows indicate the location and direction of each bottom otter trawl sample. Arrows shown outside of the search area are visualized for context, but not included in the results below.')}
if (!is.null(outputList$studyData)) {
areaMap +
    geom_segment(aes(x = outputList$mapPoints$long,
                     y = outputList$mapPoints$lat,
                     xend = outputList$mapPoints$ELONG,
                     yend = outputList$mapPoints$ELAT), arrow=arrow(length = unit(0.2,"cm")), size = 0.5, colour = "blue")
}
```
<br>
```{r RV-SAR-table}
if (!is.null(outputList$studyData)) {
  if (nrow(rvSarTable) > 0) {
    knitr::kable(rvSarTable, align="l", caption=paste("\\label{tab:rv_SAR_table}",  write_caption_blurb(rv_rr, "EN"), "Maritimes Research Vessel (RV) Survey records of species opbserved within the search area and listed by the Species at Risk Act (SARA), or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Frequency represents the number of trawls in which a given species was sampled, relative to the total number of trawls within the search area. <b>The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area.</b>"), booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
  }
}
```
<br>
```{r RV-freq-table}
if (!is.null(outputList$studyData)) {
knitr::kable(rvAllTable, align="l", caption=paste("\\label{tab:rv_freq_table}", write_caption_blurb(rv_rr, "EN"), "Maritimes Research Vessel (RV) Survey records of <u>all species</u> observed within the search area, summarized by species or species group. Frequency represents the number of trawls in which a given species was sampled, relative to the total number of trawls within the search area. <b>The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area.</b>"), booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```
