---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r dcsb-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
``` 

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **Delineation of Coral and Sponge Significant Benthic Areas in Eastern Canada (2016)** {#dcsb-section}   

```{r DCSB-load, include=FALSE}
load_rdata(c("dcsb_rr"), regionStr, env = environment())
```

```{r dcsb-meta, results='asis'}
write_meta(dcsb_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_dcsb]:
```{r DCSB-text, results='asis'}
writeLines(noquote(dcsb_rr$text$en))

```

##### *Area-Specific DCSB Search Results*

```{r DCSB-results, echo=FALSE, results='asis'}
#function for overlap
DCSBoutput <- master_intersect(dcsb_rr$data_sf, mapDataList, getRegion=TRUE)

# summary intro table
dcsbResult <- !is.null(DCSBoutput$studyData)
summaryIntroTable <- add_row_to_intro_summary(summaryIntroTable, name="[DCSB](#dcsb-section)", result=dcsbResult)


#function for overlap
Query_output_DCSB <- if(dcsbResult){
    "* The search area overlaps with identified Coral and Sponge Significant Benthic Areas in Eastern Canada."
  } else {
    "* The search area does not overlap with identified Coral and Sponge Significant Benthic Areas in Eastern Canada."
  }
writeLines(Query_output_DCSB)

```

```{r DCSB-table,  echo=FALSE, results='asis'}
DCSBTable <- DCSB_report(DCSBoutput$studyData, lang="EN")
if (!is.null(DCSBTable)){
   knitr::kable(DCSBTable, align="l", caption="Details for Coral and Sponge Significant Benthic Areas in Eastern Canada overlapping the study area.", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```

```{r DCSB-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(dcsb_rr, "EN"), 'Map showing Coral and Sponge Significant Benthic Areas in Eastern Canada within the Scotian Shelf bioregion. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Data were obtained from @OpenData_ebsa.')}
if (!is.null(DCSBoutput$regionData)){
  plot_rr_sf(regionMap, DCSBoutput$regionData, dcsb_rr$attribute)
}
```

```{r EBSA-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(ebsa_rr, "EN"), 'Map showing Coral and Sponge Significant Benthic Areas in Eastern Canada within the search area (red outline). Data were obtained from @OpenData_ebsa.')}
if(!is.null(DCSBoutput$studyData)){
  plot_rr_sf(areaMap, DCSBoutput$mapData, dcsb_rr$attribute)
}
```
