
---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r dcsb-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
``` 

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```
### **Délimitation des coraux et des éponges d'importantes zones benthiques dans l'est du Canada (2016)**  

```{r DCSB-load, include=FALSE}
load_rdata(c("dcsb_rr"), regionStr, env = environment())
```

```{r DCSB-meta, results='asis'}
write_meta(dcsb_rr, "FR")
```

Description de l’ensemble de données (tirée du dossier des données ouvertes)  [@OpenData_dcsb]:
```{r DCSB-text, results='asis'}
writeLines(noquote(dcsb_rr$text$fr))

```

#### ***Résultats de la recherche des DCSB par zone***  

```{r DCSB-results, echo=FALSE, results='asis'}
#function for overlap
DCSBoutput <- master_intersect(dcsb_rr$data_sf, mapDataList, getRegion=TRUE)
```
 
```{r DCSB-check, echo=FALSE, results='asis'}
#function for overlap
Query_output_DCSB<-if(is.null(DCSBoutput$studyData)){
    "* La zone de recherche chevauche les zones benthiques importantes de coraux et d'éponges identifiées dans l'est du Canada."
  } else {
    "* La zone de recherche ne chevauche pas les zones benthiques importantes de coraux et d'éponges identifiées dans l'est du Canada."
  }
Query_output_DCSB2<-noquote(Query_output_DCSB)

writeLines(Query_output_DCSB)

```

```{r DCSB-table,  echo=FALSE, results='asis'}
DCSBTable <- DCSB_report(DCSBoutput$studyData, lang="FR")
if (!is.null(DCSBTable)){
   knitr::kable(DCSBTable, align="l", caption="Détails pour les zones benthiques importantes de coraux et d'éponges dans l'est du Canada chevauchant la zone d'étude.</b>", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```


```{r DCSB-region-plot, fig.height=7, fig.width=11, fig.cap= 'Niveau de qualité : Élevée. Niveau de sécurité : Aucun. Carte montrant les zones benthiques importantes de coraux et d\'éponges dans l\'est du Canada dans la biorégion du plateau néo-écossais. La zone de recherche est représentée par un contour rouge et une vue plus détaillée est présentée dans la figure ci-dessous, si des données pertinentes sont présentes. Les données ont été obtenues à partir de @OpenData_dcsb.'}
if (!is.null(DCSBoutput$regionData)){
  plot_rr_sf(regionMap, DCSBoutput$regionData, dcsb_rr$attribute,legendName= "Zones Benthiques Importantes", alpha = 0.6)
}
```

```{r DCSB-area-plot, fig.height=7, fig.width=11, fig.cap= 'Niveau de qualité : Élevée. Niveau de sécurité : Aucun. Carte montrant les zones benthiques importantes de coraux et d\'éponges dans l\'est du Canada dans la zone de recherche (contour rouge). Les données ont été obtenues à partir de @OpenData_dcsb.'}
if(!is.null(DCSBoutput$studyData)){
  plot_rr_sf(areaMap, DCSBoutput$mapData, dcsb_rr$attribute, legendName= "Zones Benthiques Importantes", alpha = 0.6)
}
```
