---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r benthic-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")} 
```

```{r benthic-load-common-ha, child = here::here("reports/sections/commonSections/commonHA.Rmd")} 
``` 

```{r eval = FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())
}
```

### **Fishing Effort Within Significant Benthic Areas in Canada's Atlantic and Eastern Arctic Marine Waters** {#benthic-effort-section}    

```{r benthicEffort-load, include=FALSE}
load_rdata(c("benthicEffort_rr"), "MAR", env = environment())
```

```{r benthicEffort-meta, results='asis'}
write_meta(benthicEffort_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_benthicEffort]:
```{r benthicEffort-text, results='asis'}
writeLines(noquote(benthicEffort_rr$text$en))
```

##### *Area-Specific Fishing Effort Within Significant Benthic Areas Search Results*

```{r benthicEffort-results, echo=FALSE, results='asis'}
outputListBenthicEffort <- master_intersect(benthicEffort_rr$data_sf, mapDataList,
                                           getRegion=TRUE)

```

```{r benthicEffort-haTable, echo=FALSE, results='asis'}
if (!is.null(outputListBenthicEffort$studyData)) {
  rrEnv$haClassTable$`Benthic Fishing Effort` <- list("Coastal" = FALSE, 
                                                    "Offshore" = TRUE, 
                                                    "Shoreline" = FALSE)
}
```


```{r benthicEffort-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
benthicEffortReport <- if (is.null(outputListBenthicEffort$mapData)) {
  "* There are no relevant records of fishing effort in bethic areas for this search area."
} else {
  "* There are relevant records of fishing effort in bethic areas for this search area."
}
writeLines(noquote(benthicEffortReport))
```
<br>
```{r benthicEffort-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(benthicEffort_rr, "EN"), 'Maps showing the benthic fishing effort (%) within the Scotian Shelf bioregion from @OpenData_benthicEffort. For a full description of how benthic fishing effort was calculated, refer to @DFO2017_Del and @Koen-Alonso2021. The search area is shown as a red outline, and a more detailed view if shown in the figure below, if relevant data are present. Dashed grey lines indicate international boundaries.')}
if (!is.null(outputListBenthicEffort$mapData)) {
  plot_rr_sf(mapDataList$regionMap, outputListBenthicEffort$regionData, bgCutoff=15)
}
```

```{r benthicEffort-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(benthicEffort_rr, "EN"), 'Maps showing the benthic fishing effort (%) within the Scotian Shelf bioregion from @OpenData_benthicEffort. For a full description of how benthic fishing effort was calculated, refer to @DFO2017_Del and @Koen-Alonso2021. The search area is shown as a red outline.')}
if (!is.null(outputListBenthicEffort$mapData)) {
  plot_rr_sf(mapDataList$areaMap, outputListBenthicEffort$mapData, bgCutoff=15)
}
```

