---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r obis-fish-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())
}
```

```{r obis-gbif-load, include=FALSE}
load_rdata(c("obisFish_rr", "gbifFish_rr"), regionStr, env = environment())
```

```{r child = here::here("reports/sections/obis/obisCommon_fr.Rmd"), eval=!exists('commonObis')}
# chunk will only run if commonObis variable does not exist, set in common obis, removed in commonIntro.
```

#### ***Résultats de recherche du SIBO sur les poissons et les invertébrés par zone***

```{r obis-results, include=FALSE, cache=FALSE}
outputList <- master_intersect(obisFish_rr$data_sf, mapDataList, Year = minYear)

obisTable <- create_sar_tables(outputList$studyData, listed_species, extraCols = c("URL", "Citation"))$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[OBIS](#OBIS-section)", obisTable, "Common Name", "Common Name")
```

```{r obis-check, echo=FALSE, results='asis',}
Report_obis <- if (is.null(outputList$studyData)) {
  "* There are no relevant records in the Ocean Biodiversity Information System (OBIS) for this search area."
} else {
  "* There are relevant records in the Ocean Biodiversity Information System (OBIS) for this search area."
}
Report_obis<-noquote(Report_obis)
writeLines(Report_obis)
```

```{r obis-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(obisFish_rr, "FR"), 'Map of Ocean Biodiversity Information System (OBIS) observation records (black circles) of fish or invertebrate species observed within the search area (red outline) and listed by the Species at Risk Act (SARA), and/or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Species designated as “Not at Risk” by SARA or COSEWIC are not included in this search. Observations displayed outside of the search area are visualized for context, but not included in the survey results listed below. The absence of a species in this figure should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area.')}
if (!is.null(outputList$studyData)) {
  plot_rr_sf(areaMap, outputList$mapData)
}
```

```{r obis-table, echo=FALSE, results='asis'}
if (!is.null(outputList$studyData)) {
  knitr::kable(obisTable, align="l", caption=paste(write_caption_blurb(obisFish_rr, "FR"), "Ocean Biodiversity Information System (OBIS) observation records of fish and invertebrate species observed within the search area, and listed by the Species At Risk Act (SARA), and/or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Species designated as “Not at Risk” by SARA or COSEWIC are not included in this search. URLs contain links to a complete dataset description. The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area."), booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```


#### ***Area-specific GBIF  search results***

```{r gbif-results, cache=FALSE, include=FALSE}
inaturalist_sf = subset(gbifFish_rr$data_sf, title == "iNaturalist Research-grade Observations")
inaturalistClipped <- master_intersect(inaturalist_sf, mapDataList)
inaturalistTable <- create_sar_tables(inaturalistClipped$studyData, listed_species, extraCols = c("URL", "Citation"))$sarData

otherGbif_sf = subset(gbifFish_rr$data_sf, title != "iNaturalist Research-grade Observations")
gbifClipped <- master_intersect(otherGbif_sf, mapDataList)
gbifTable <- create_sar_tables(gbifClipped$studyData, listed_species, extraCols = c("URL", "Citation"))$sarData


# Add to summary tables!

```

```{r gbif-check, comment="", prompt=TRUE, echo=FALSE, results='asis'}
reportGbif <-  if (is.null(gbifClipped$studyData)) {
  "*	There are no relevant records in the Global Biodiversity Information Facility (GBIF) for this search area."
} else if (is.null(inaturalistClipped$studyData)){
  "*	There are relevant records in the Global Biodiversity Information Facility (GBIF) for this search area."
} else {
  "*	There are relevant records in the Global Biodiversity Information Facility (GBIF) including iNaturalist entries for this search area."  
}
writeLines(reportGbif)
```

```{r gbif-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(gbifFish_rr, "FR"), 'Species designated as “Not at Risk” by SARA or COSEWIC are not included in this search. Observations displayed outside of the search area are visualized for context, but not included in the survey results listed below. The absence of a species in this figure should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area.')}
if (!is.null(gbifClipped$studyData)) {
  plot_rr_sf(areaMap, gbifClipped$mapData, attribute=gbifFish_rr$attribute)
}
```

```{r gbif-table, echo=FALSE, results='asis'}
if (!is.null(gbifClipped$studyData)) {
  knitr::kable(gbifTable, align="l", caption=paste(write_caption_blurb(gbifFish_rr, "FR"), "Global Biodiversity Information Facility (GBIF) observation records of fish and invertebrate species observed within the search area, and listed by the Species At Risk Act (SARA), and/or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Species designated as “Not at Risk” by SARA or COSEWIC are not included in this search. URLs contain links to a complete dataset description. The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. "), booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```

```{r inaturalist-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(gbifFish_rr, "FR"), 'Research-grade iNaturalist observations within the search area (red outline) of fish or invertebrate species that have been added to the Global Biodiversity Information Facility (GBIF). Species included have been listed by the Species at Risk Act (SARA), and/or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Observations displayed outside of the search area are visualized for context, but not included in the survey results listed below. Observations are coloured to show coordinate uncertainties of the data, where observations with coordinate uncertainties >20 km represent locations that have been obscured due to geoprivacy concerns (e.g., hunting). NAs refer to observations with no provided coordinate uncertainty. The absence of a species in this figure should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. ')}
if (!is.null(inaturalistClipped$studyData)) {
  plot_rr_sf(areaMap, inaturalistClipped$mapData, attribute=gbifFish_rr$attribute)
}
```

```{r inaturalist-table, echo=FALSE, results='asis'}
if (!is.null(inaturalistClipped$studyData)) {
  knitr::kable(inaturalistTable, align="l", caption=paste(write_caption_blurb(gbifFish_rr, "FR"), "Research-grade iNaturalist observations within the search area (red outline) of fish or invertebrate species that have been added to the Global Biodiversity Information Facility (GBIF). Species included have been listed by the Species at Risk Act (SARA), and/or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Species designated as “Not at Risk” by SARA or COSEWIC are not included in this search. Observations displayed outside of the search area are visualized for context, but not included in the survey results listed below. Observations are coloured to show coordinate uncertainties of the data, where observations with coordinate uncertainties >20 km represent locations that have been obscured due to geoprivacy concerns (e.g., hunting). NAs refer to observations with no provided coordinate uncertainty. The absence of a species in this figure should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area."), booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```
