---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r tuna-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { 
  # load in generic data, e.g.functions, study area, and base maps into the 
  # environment, when knitting, these will be loaded through the child rmd.
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment())
}
```

### **Bluefin Tuna Presence ** {#tuna-section}

```{r tuna-load, include=FALSE}
# load in section specific data
load_rdata(c("tuna_rr"), regionStr, env = environment())

```

```{r tuna-meta, results='asis'}
# metadata blurb at start of each section
write_meta(tuna_rr, "EN")
```

```{r tuna-text, results='asis'}
# metadata blurb at start of each section
  writeLines(tuna_rr$text$en, sep="  \n")
```

#### *Area-specific Bluefin Tuna Presence results*
```{r tuna-results, include=FALSE, cache=FALSE}
# clip the data to the Study and Map areas:
tunaOutputList <- master_intersect(tuna_rr$data_sf, mapDataList)

tunaTable <- tuna_table(tunaOutputList$studyData)

```

```{r tuna-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
tunaReport <- if (is.null(tunaOutputList$studyData)) {
  "* There are no relevant Bluefin Tuna presence records for this search area."
} else {
  "* There are relevant Bluefin Tuna presence records for this search area."
}
writeLines(noquote(tunaReport))
```

```{r tuna-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(tuna_rr, "EN"), 'Map showing the search area defined by the user (red outline) used to query information from Bluefin Tuna presence records .')}
if (!is.null(tunaOutputList$studyData)) {
  # common plotting function:
  plot_rr_sf(areaMap, tunaOutputList$mapData, attribute = 
               tuna_rr$attribute)
}
```

```{r tuna-table}
if (!is.null(tunaTable)) {
    knitr::kable(tunaTable, align = "l", caption = paste("\\label{tab:tunaTable}", write_caption_blurb(tuna_rr, "EN"), "Records of tuna presence contained within the search area. The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. </b>"), booktabs = T, escape = F, linesep = "") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}

```
