
---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r IMRPSAR-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **IMRP Species at Risk Section**  {#IMRPSAR-section}

```{r IMRP-rv-load, include=FALSE}
load_rdata(c("rv_rr"), "MAR", env = environment())
```

```{r IMRP-RV-results, include=FALSE, cache=FALSE}
outputList <- master_intersect(rv_rr$data_sf, mapDataList, Year = minYear)


tableList <- create_table_RV(outputList$studyData, listed_species)
rvSarTable <- tableList$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[RV](#RV-section)", rvSarTable, "Common Name", "Individuals")

```

```{r IMRP-obis-load, include=FALSE}
load_rdata(c("obis_rr"), regionStr, env = environment())
```

```{r IMRP-obis-results, include=FALSE, cache=FALSE}
outputList <- master_intersect(obis_rr$data_sf, mapDataList, Year = minYear)

obisTable <- create_sar_tables(outputList$studyData, listed_species, extraCols = c("URL", "Citation"))$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[OBIS](#OBIS-section)", obisTable, "Common Name", "Common Name")
```

```{r IMRP-gbif-load, include=FALSE}
load_rdata(c("gbif_rr"), regionStr, env = environment())
```

```{r IMRP-gbif-results, cache=FALSE, include=FALSE}
inaturalist_sf = subset(gbif_rr$data_sf, title == "iNaturalist Research-grade Observations")
inaturalistClipped <- master_intersect(inaturalist_sf, mapDataList)

inaturalistTable <- create_sar_tables(inaturalistClipped$studyData, listed_species, extraCols = c("URL", "Citation"))$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[iNaturalist](#gbif-section)", inaturalistTable, "Common Name", "Common Name")

otherGbif_sf = subset(gbif_rr$data_sf, title != "iNaturalist Research-grade Observations")
gbifClipped <- master_intersect(otherGbif_sf, mapDataList)

gbifTable <- create_sar_tables(gbifClipped$studyData, listed_species, extraCols = c("URL", "Citation"))$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[GBIF](#gbif-section)", gbifTable, "Common Name", "Common Name")

```

### **IMRP Multi-Species Synthesis**

```{r IMRP-sar-obs-summary-table}
absentCode <- "\U2013"
      presentCode <- "\U2714"
summarySarTable[is.na(summarySarTable)] <- absentCode
formatedSarTable <- summarySarTable

```

```{r IMRP-sar-hab-summary-table}
  summaryHabTable[is.na(summaryHabTable)] <- "\U2013"

  # add column for observations from sar table
  obsColumn <- apply(summarySarTable, 1, function(r) any(r %in% c(presentCode)))
  summaryHabTable$Obs <- ifelse(obsColumn, presentCode, absentCode)

  names(summaryHabTable) <- c("Species", "COSEWIC", "SARA", "Observations", "SAR Range", "SDM", "Important Habitat", "Critical Habitat")
  summaryHabTable <- summaryHabTable %>% 
    filter(!(Observations == absentCode & `SAR Range` == absentCode & SDM == absentCode & `Important Habitat` == absentCode & `Critical Habitat` == absentCode))

```

```{r IMRP-output-hab-table}
knitr::kable(summaryHabTable, align="l", caption = "Regional synthesis of data and data products of species contained within the search area that are listed by the Species At Risk Act (SARA), and/or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Data points (observations) are summarized in more detail in the subsequent table. A description of the different sources of information for Species at Risk is available in the infographic: https://github.com/dfo-mar-odis/shinySpatialApp/blob/master/app/data/misc/SAR-information-type-reproducible-reports.pdf). The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. Outputs are not suitable for real-time, dynamic spatial planning.", booktabs = T, escape = F, linesep = "") %>%
  kableExtra::kable_styling(bootstrap_options = "striped", full_width = T, position = "left")
```