---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r IMRPebs-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **Ecologically and Biologically Significant Areas (EBSAs) For Environmental Response** {#IMRPebs-section}

```{r IMRPEBSA-load, include=FALSE}
load_rdata(c("IMRPebs_rr"), regionStr, env = environment())
```
<details>
  <summary>Click for Text Information </summary>
  
```{r IMRPEBS-meta, results='asis'}
write_meta(IMRPebs_rr, "EN")
```

A Story Map summarizing work that has been done to identify EBSAs in the Maritimes Region is available here: <https://gisp.dfo-mpo.gc.ca/portal/apps/MapJournal/index.html?appid=b91f85de60f44a7b90633e4b43e3916a>

Dataset description from the Open Data record [@OpenData_ebsa]:

```{r IMRPEBS-text, results='asis'}
writeLines(noquote(IMRPebs_rr$text$en))

```

</details> 

##### *Area-Specific EBSA Search Results*

```{r IMRPEBS-results, echo=FALSE, results='asis'}
#function for overlap
EBSAoutput <- master_intersect(IMRPebs_rr$data_sf, mapDataList, getRegion=TRUE)

ebsaResult <- !is.null(EBSAoutput$studyData)

#function for overlap
Query_output_EBSA <- if(ebsaResult){
    "* The search area overlaps with identified Ecologically and Biologically Significant Areas (EBSAs)."
  } else {
    "* The search area does not overlap with identified Ecologically and Biologically Significant Areas (EBSAs)."
  }
writeLines(Query_output_EBSA)

```

```{r IMRPEBS-tablea,  echo=FALSE, results='asis'}

ebsaCritTab <- additionalInfo %>% 
  dplyr::filter(additionalInfo$FID %in% EBSAoutput$studyData$FID) %>% 
  dplyr::select(Name,ends_with("Criteria")) %>% 
  dplyr::rename("Uniqueness" = Uniqueness.Criteria, "Aggregation" = Aggregation.Criteria, "Fitness Consequences" = Fitness.Consequences.Criteria, "Resilience" = Resilience.Criteria, "Naturalness" = Naturalness.Criteria)

if (!is.null(EBSAoutput$studyData)){
   knitr::kable(ebsaCritTab, align="l", caption="Criteria met by each EBSA overlapping the study area.", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = T, position = "left")
}
```

```{r IMRPEBS-tableb,  echo=FALSE, results='asis'}

IMRPebsaTabDat <- additionalInfo %>% 
  dplyr::filter(additionalInfo$FID %in% EBSAoutput$studyData$FID) %>% 
  dplyr::select(Name,Feature,PDF.Link) %>% 
  dplyr::rename("EBSA Document Link" = PDF.Link)

if (!is.null(EBSAoutput$studyData)){
   knitr::kable(IMRPebsaTabDat, align="l", caption="Features for Ecologically and Biologically Significant Areas (EBSAs) overlapping the study area.", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = T, position = "left")
}
```

```{r IMRPEBS-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(IMRPebs_rr, "EN"), 'Map showing Ecologically and Biologically Significant Areas (EBSAs) within the Scotian Shelf bioregion. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Data were obtained from @OpenData_ebsa.')}
if (!is.null(EBSAoutput$regionData)){
  plot_rr_sf(regionMap, EBSAoutput$regionData, attribute ="None")
}
```

```{r IMRPEBS-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(IMRPebs_rr, "EN"), 'Map showing Ecologically and Biologically Significant Areas (EBSAs) within the search area (red outline). Data were obtained from @OpenData_ebsa.')}
if(!is.null(EBSAoutput$studyData)){
  areaLabels <- EBSAoutput$mapData %>% dplyr::select(c("Name"))
  plot_rr_sf(areaMap, EBSAoutput$mapData, IMRPebs_rr$attribute, labelData = areaLabels, labelAttribute = "Name", alpha=0.7)
}
```
