---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r ebsa-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
``` 

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **Ecologically and Biologically Significant Areas (EBSAs)** {#ebsa-section}   

```{r EBSA-load, include=FALSE}
load_rdata(c("ebsa_rr"), regionStr, env = environment())
```

```{r EBSA-meta, results='asis'}
write_meta(ebsa_rr, "EN")
```
A Story Map summarizing work that has been done to identify EBSAs in the Maritimes Region is available here: https://gisp.dfo-mpo.gc.ca/portal/apps/MapJournal/index.html?appid=b91f85de60f44a7b90633e4b43e3916a

Dataset description from the Open Data record [@OpenData_ebsa]:
```{r EBSA-text, results='asis'}
writeLines(noquote(ebsa_rr$text$en))

```

##### *Area-Specific EBSA Search Results*

```{r EBSA-results, echo=FALSE, results='asis'}
#function for overlap
EBSAoutput <- master_intersect(ebsa_rr$data_sf, mapDataList, getRegion=TRUE)

# summary intro table
ebsaResult <- !is.null(EBSAoutput$studyData)
summaryIntroTable <- add_row_to_intro_summary(summaryIntroTable, name="[EBSA](#ebsa-section)", result=ebsaResult)


#function for overlap
Query_output_EBSA <- if(ebsaResult){
    "* The search area overlaps with identified Ecologically and Biologically Significant Areas (EBSAs)."
  } else {
    "* The search area does not overlap with identified Ecologically and Biologically Significant Areas (EBSAs)."
  }
writeLines(Query_output_EBSA)

```

```{r EBSA-table,  echo=FALSE, results='asis'}
EBSATable <- EBSA_report(EBSAoutput$studyData, lang="EN")
if (!is.null(EBSATable)){
   knitr::kable(EBSATable, align="l", caption="Details for Ecologically and Biologically Significant Areas (EBSAs) overlapping the study area.", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```

```{r EBSA-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(ebsa_rr, "EN"), 'Map showing Ecologically and Biologically Significant Areas (EBSAs) within the Scotian Shelf bioregion. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Data were obtained from @OpenData_ebsa.')}
if (!is.null(EBSAoutput$regionData)){
  plot_rr_sf(regionMap, EBSAoutput$regionData, ebsa_rr$attribute)
}
```

```{r EBSA-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(ebsa_rr, "EN"), 'Map showing Ecologically and Biologically Significant Areas (EBSAs) within the search area (red outline). Data were obtained from @OpenData_ebsa.')}
if(!is.null(EBSAoutput$studyData)){
  plot_rr_sf(areaMap, EBSAoutput$mapData, ebsa_rr$attribute)
}
```
