---
title: "Reproducible Report for internal DFO use only: DRAFT"
subtitle: {{u_text}}
author: "Report generated by: {{u_name}} ({{u_email}})"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  bookdown::pdf_document2:
    number_sections: FALSE
    theme: paper
    toc: true
    toc_depth: 5
  pdf_document:
    toc: true
  word_document:
    toc: true
bibliography: ../data/mybiblio.bib
---

<style>
table {background-color: white !important;color: black !important;}
caption {color: black !important;}
a:link {color: #002080;}
a:visited {color: #008040;}
a:hover {color: #006080;}
</style>

```{r setup and libraries, echo=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE, fig.align="left")
```

```{r load data and functions, echo=FALSE, include=FALSE, cache=FALSE}
minYear <- 2010
load("../data/OpenData.RData")
load("../data/OpenData_sardist.RData")
load("../data/SecureData.RData")
#load("\\\\ent.dfo-mpo.ca\\ATLShares\\Science\\BIODataSvc\\SRC\\Reproducible_Reporting\\data\\SecureData.Rdata")
lapply(list.files("../R", pattern = ".[Rr]$", full.names = TRUE),source)
```

```{r Search Area and setup.R, echo=FALSE, include=FALSE, cache=FALSE}
#studyArea <- sf::st_read("{{path_to_geoms}}")
#studyArea <- sf::st_read("geoms_slc.geojson")

# Uncomment the following to test fixed polygon:
# studyArea <- st_read("../studyAreaTest/geoms_slc_test.geojson")#Offshore
 studyArea <- st_read("../studyAreaTest/geoms_slc_coastal_test.geojson")#coastal 
# studyArea <- st_read("../studyAreaTest/geoms_slc_no_land.geojson")#no land

site <- sf::st_centroid(studyArea) 
```

```{r parameters for area_map.r, echo=FALSE, include=FALSE, cache=FALSE}
# The following defines studyBox geometry "look". studyBox_geom is input into area map or can be added to any map later
studyBox_geom <- geom_sf(data=studyArea, fill=NA, col="red", size=1) 

# The following plots area map using function (output is a list)
areaMapList<-area_map(studyArea, site, land50k_sf, 5, bounds_sf, studyBox_geom)

# The following separates items in the output list: first item is a map and second is a bounding box of the map
areaMap=areaMapList[[1]] # map
bboxMap=areaMapList[[2]] #bounding box of the map
```

<!-- # ```{r child = c('../Rmd/report_cetaceans_EN.Rmd', 'report_fish_EN.Rmd', 'report_habitat_EN.Rmd', 'report_planning_EN.Rmd', 'report_SARA_EN.Rmd')} -->


 ```{r child = '../Rmd/report_fish_EN.Rmd'}
 ```


<!-- END  -->


{{add_main_sections}}

<!-- HABITAT -->

{{add_appendix}}

<!-- ZIEB -->

{{add_ebsa_section}}

<!-- FIN GÉNÉRIQUE -->

