## **AREAS DESIGNATED FOR SPATIAL PLANNING**  

### **Ecologically and Biologically Significant Areas (EBSA)**  
Contact: <carissa.philippe@dfo-mpo.gc.ca>  
Last retrieved on: January 21, 2021 from Open Data  
<https://open.canada.ca/data/en/dataset/d2d6057f-d7c4-45d9-9fd9-0a58370577e0>  
Quality Tier: High  
Security level: none  

Dataset description from the Open Data record [@OpenData_ebsa]: Ecologically and Biologically Significant Areas (EBSAs) are areas within Canada's oceans that have been identified through formal scientific assessments as having special biological or ecological significance when compared with the surrounding marine ecosystem. Failure to define an area as an EBSA does not mean that it is unimportant ecologically. All areas serve ecological functions to some extent and require sustainable management. Rather, areas identified as EBSAs should be viewed as the most important areas where, with existing knowledge, regulators and marine users should be particularly risk averse to ensure ecosystems remain healthy and productive. EBSA information is used to inform marine planning, including environmental assessment and the siting of marine-based activities, by:

- Informing and guiding project-specific or regional environmental assessments
- Informing and guiding industries and regulators in their planning and operations, for example: EBSAs have been acknowledged and referred to (often as "Special Areas" or "Potentially Sensitive Areas") in oil and gas related assessments
- EBSA information has been provided to proponents of submarine cable projects to be used for route planning purposes
- Informing and guiding Integrated Oceans Management (IOM) process within five Large Ocean Management Areas (LOMAs) and twelve marine bioregions
- Serving as a basis for the identification of Areas of Interest (AOIs) and of Marine Protected Areas (MPAs) (individually and in the context of planning bioregional networks of MPAs).

#### ***Area-specific EBSA search results***  

**under-development**

```{r, fig.height=8, fig.width=11, fig.cap= 'Quality Tier: High. Security level: none. Map showing Ecologically and Biologically Significant Areas (EBSA; pink) relative to the search area defined by the user: location of the proposed project/activity is highlighted in yellow (input polygon), surrounded by an exposure zone or user-defined buffer area in blue.'}
#plot_EBSA(EBSA_sf, studyArea, land10m_sf, 300)
```