---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r opprrpe-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { 
  # load in generic data, e.g.functions, study area, and base maps into the 
  # environment, when knitting, these will be loaded through the child rmd.
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment())
}
```

### **Oceans Protection Plan Regional Response Planning Extents ** {#opprrpe-section}

```{r opprrpe-load, include=FALSE}
# load in section specific data
load_rdata(c("opprrpe_rr"), regionStr, env = environment())

```

```{r opprrpe-meta, results='asis'}
# metadata blurb at start of each section
write_meta(opprrpe_rr, "EN")
```

```{r opprrpe-text, results='asis'}
# metadata blurb at start of each section
  writeLines(opprrpe_rr$text$en, sep="  \n")
```

#### *Area-specific Oceans Protection Plan Regional Response Planning Extents results*
```{r opprrpe-results, include=FALSE, cache=FALSE}
# clip the data to the Study and Map areas:
opprrpeOutputList <- master_intersect(opprrpe_rr$data_sf, mapDataList, getRegion = TRUE)

```

```{r opprrpe-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
opprrpeReport <- if (is.null(opprrpeOutputList$studyData)) {
  "* There are no relevant Oceans Protection Plan Regional Response Planning Extents for this search area."
} else {
  "* There are relevant Oceans Protection Plan Regional Response Planning Extents for this search area."
}
writeLines(noquote(opprrpeReport))
```

```{r opprrpe-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(opprrpe_rr, "EN"), 'Regional Map showing the search area defined by the user (red outline) used to query information from Oceans Protection Plan Regional Response Planning Extents.')}
if (!is.null(opprrpeOutputList$regionData)) {
  # common plotting function:
  opprrpePlotList <- plot_rr_sf(regionMap, opprrpeOutputList$regionData, attribute = opprrpe_rr$attribute, getColorMap = TRUE)
  opprrpePlotList$polyMap
}
```

```{r opprrpe-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(opprrpe_rr, "EN"), 'Map showing the search area defined by the user (red outline) used to query information from Oceans Protection Plan Regional Response Planning Extents.')}
if (!is.null(opprrpeOutputList$studyData)) {
  # common plotting function:
  plot_rr_sf(areaMap, opprrpeOutputList$mapData, attribute = 
               opprrpe_rr$attribute, colorMap=opprrpePlotList$colorMap)
}
```

