---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r docks-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r docks-load-common-ha, child = here::here("reports/sections/commonSections/commonHA.Rmd")} 
``` 

```{r eval = FALSE}
if (FALSE) { 
  # load in generic data, e.g.functions, study area, and base maps into the 
  # environment, when knitting, these will be loaded through the child rmd.
  lapply(list.files(here::here("app/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment())
}
```

### **Man-made solid classification from the Atlantic Shoreline Classification dataset ** {#docks-section}

```{r docks-load, include=FALSE}
# load in section specific data
load_rdata(c("docks_rr"), regionStr, env = environment())

```

```{r docks-meta, results='asis'}
# metadata blurb at start of each section
write_meta(docks_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_docks]:
```{r docks-text, results='asis'}
writeLines(noquote(docks_rr$text$en))

```


##### *Area-Specific Man-Made Solid Classification Search Results*
```{r docks-results, include=FALSE, cache=FALSE}
# clip the data to the Study and Map areas:
docksOutputList <- master_intersect(docks_rr$data_sf, mapDataList,
                                    getRegion=TRUE)

```


```{r docks-haTable, echo=FALSE, results='asis'}
if (!is.null(docksOutputList$studyData)) {
  rrEnv$haClassTable$`Manmade Structures` <- list("Coastal" = FALSE, 
                                                "Offshore" = FALSE, 
                                                "Shoreline" = TRUE)
}
```

```{r docks-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
docksReport <- if (is.null(docksOutputList$studyData)) {
  "* There are no relevant records of man-made solids for this search area."
} else {
  "* There are relevant records of man-made solids for this search area."
}
writeLines(noquote(docksReport))
```

```{r docks-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(docks_rr, "EN"), 'Records of man-made solids within the Scotian Shelf bioregion. Records were obtained from the Atlantic Shoreline Classification dataset in Open Data [@OpenData_docks]. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Dashed grey lines indicate international boundaries.')}
if (!is.null(docksOutputList$studyData)) {
    plot(plot_rr_sf(regionMap, docksOutputList$regionData, lwd = 2, color=rrBlue)) 
}
```

```{r docks-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(docks_rr, "EN"), 'Records of man-made solids within the search area defined by the user (red outline). Records were obtained from the Atlantic Shoreline Classification dataset in Open Data [@OpenData_docks]')}
if (!is.null(docksOutputList$studyData)) {
    plot(plot_rr_sf(areaMap, docksOutputList$mapData, lwd = 2, color=rrBlue)) 
}
```

