---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r imAcoustic-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { 
  # load in generic data, e.g.functions, study area, and base maps into the 
  # environment, when knitting, these will be loaded through the child rmd.
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment())
}
```

```{r imAcoustic-load, include=FALSE}
# load in section specific data
load_rdata(c("imAcoustic_rr"), regionStr, env = environment())

```

### **`r imAcoustic_rr$datasetName` ** {#imAcoustic-section}



```{r imAcoustic-meta, results='asis'}
# metadata blurb at start of each section
write_meta(imAcoustic_rr, "EN")
```

```{r imAcoustic-text, results='asis'}
# metadata blurb at start of each section
  writeLines(imAcoustic_rr$text$en, sep="  \n")
```

#### *Area-specific `r imAcoustic_rr$datasetName` results*
```{r imAcoustic-results, include=FALSE, cache=FALSE}
# clip the data to the Study and Map areas:
outputList <- master_intersect(imAcoustic_rr$data_sf, mapDataList)

# summary intro table
introResult <- !is.null(outputList$studyData)
summaryIntroTable <- add_row_to_intro_summary(summaryIntroTable, name="[Video and Acoustic Survey](#imAcoustic-section)", result=introResult)



```

```{r imAcoustic-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
outputReport <- if (is.null(outputList$studyData)) {
  paste("* There are no relevant video and acoustic survey of seaweed records for this search area.")
} else {
  paste("* There are relevant video and acoustic survey of seaweed records for this search area.")
}
writeLines(noquote(outputReport))
```

```{r imAcoustic-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(imAcoustic_rr, "EN"), 'Map showing the search area defined by the user (red outline)and boundries of the six study area zones used for the video and acoustic survey of seaweed.')}
if (!is.null(outputList$studyData)) {
  # common plotting function:
  plot_rr_sf(areaMap, outputList$mapData, attribute = 
               imAcoustic_rr$attribute)
}
```
