---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r calanus-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
``` 

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **Calanus spp. size and lipid content metrics in North Atlantic, 1977-2019** {#calanus-section}   

```{r calanus-load, include=FALSE}
load_rdata(c("calanus_rr"), regionStr, env = environment())
```

```{r calanus-meta, results='asis'}
write_meta(calanus_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_calanus]:
```{r calanus-text, results='asis'}
writeLines(noquote(calanus_rr$text$en))

```

##### *Area-Specific Calanus content metrics Search Results*

```{r calanus-results, echo=FALSE, results='asis'}
#function for overlap
calanusOutput <- master_intersect(calanus_rr$data_sf, mapDataList, getRegion=TRUE)

# summary intro table
calanusResult <- !is.null(calanusOutput$studyData)
summaryIntroTable <- add_row_to_intro_summary(summaryIntroTable, name="[calanus](#calanus-section)", result=calanusResult)

#function for overlap
Query_output_calanus <- if(calanusResult){
    "* The search area overlaps with Calanus spp. size and lipid content metrics."
  } else {
    "* The search area does not overlap with Calanus spp. size and lipid content metrics."
  }
writeLines(Query_output_calanus)

```

```{r calanus-table,  echo=FALSE, results='asis'}
calanusTable <- NULL
if(calanusResult){
  calanusTable <- unique(dplyr::select(calanusOutput$studyData, c("Year", "Station")))
  calanusTable <- sf::st_drop_geometry(calanusTable)
  rownames(calanusTable) <- NULL
} 

if (!is.null(calanusTable)){
   knitr::kable(calanusTable, align="l", caption="Details for Ecologically and Biologically Significant Areas (calanuss) overlapping the study area.", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```

```{r calanus-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(calanus_rr, "EN"), 'Map showing Ecologically and Biologically Significant Areas (calanuss) within the Scotian Shelf bioregion. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Data were obtained from @OpenData_calanus.')}
if (!is.null(calanusOutput$regionData)){
  plot_rr_sf(regionMap, calanusOutput$regionData, calanus_rr$attribute)
}
```

```{r calanus-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(calanus_rr, "EN"), 'Map showing Ecologically and Biologically Significant Areas (calanuss) within the search area (red outline). Data were obtained from @OpenData_calanus.')}
if(!is.null(calanusOutput$studyData)){
  plot_rr_sf(areaMap, calanusOutput$mapData, calanus_rr$attribute)
}
```
