---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r child = here::here("sections/commonSections/commonIntro.Rmd")}
if (FALSE) { # load in data for manual knitting:
  lapply(list.files(here::here("app/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment(), regionStr = regionStr)
}
```

### **Template** {#template-section}

```{r template-load, include=FALSE}
load_rdata(c("template_rr"), regionStr, env = environment())

```

```{r template-meta, results='asis'}
# metadata blurb at start of each section
write_meta(template_rr, "EN")
```

#### ***Area-specific Template results***
```{r template-results, include=FALSE, cache=FALSE}

templateOutputList <- master_intersect(template_rr$data_sf, mapDataList)

tableList <- create_sar_tables(templateOutputList$studyData, listed_species)
templateAllTable <- tableList$allSpecies
templateSarTable <- tableList$sarData
```

```{r template-check, echo=FALSE, results='asis',}
templateReport <- if (is.null(templateOutputList$studyData)) {
  "* There are no relevant template records for this search area."
} else {
  "* There are relevant template records for this search area."
}
writeLines(noquote(templateReport))
```

```{r template-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(template_rr, "EN"), 'Map showing the search area defined by the user (red outline) used to query information from template records.')}
if (!is.null(templateOutputList$studyData)) {
  plot_rr_sf(areaMap, templateOutputList$mapData, attribute = 
               template_rr$attribute)
}
```
<br>
```{r template-table}
if (!is.null(templateOutputList$studyData)) {
  if (nrow(templateSarTable) > 0) {
    knitr::kable(templateSarTable, align = "l", caption = paste("\\label{tab:template_table}", write_caption_blurb(template_rr, "EN"), "Template records of species contained within the search area and listed by the Species At Risk Act (SARA), or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). Frequency represents the subset of the sampling locations out of the total where each species is present. The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. </b>"), booktabs = T, escape = F, linesep = "") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
  }
}
```
