---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r substrate-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
``` 

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **A substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region - A substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region** {#substrate-section}   

```{r SUBSTRATE-load, include=FALSE}
load_rdata(c("substrate_rr"), regionStr, env = environment())
```

```{r SUBSTRATE-meta, results='asis'}
write_meta(substrate_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_substrate]:
```{r SUBSTRATE-text, results='asis'}
writeLines(noquote(substrate_rr$text$en))

```

##### *Area-Specific substrate Search Results*

```{r SUBSTRATE-results, echo=FALSE, results='asis'}
#function for overlap
SUBSTRATEoutput <- master_intersect(substrate_rr$data_sf, mapDataList, getRegion=TRUE)

# summary intro table
substrateResult <- !is.null(SUBSTRATEoutput$studyData)
summaryIntroTable <- add_row_to_intro_summary(summaryIntroTable, name="[SUBSTRATE](#substrate-section)", result=substrateResult)


#function for overlap
Query_output_SUBSTRATE <- if(substrateResult){
    "* The search area overlaps with identified substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region."
  } else {
    "* The search area does not overlap with identified substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region."
  }
writeLines(Query_output_SUBSTRATE)

```

```{r SUBSTRATE-table,  echo=FALSE, results='asis'}
SUBSTRATETable <- SUBSTRATE_report(SUBSTRATEoutput$studyData, lang="EN")
if (!is.null(SUBSTRATETable)){
   knitr::kable(SUBSTRATETable, align="l", caption="Details for substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region overlapping the study area.", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```

```{r SUBSTRATE-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(substrate_rr, "EN"), 'Map showing substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Data were obtained from @OpenData_substrate.')}
if (!is.null(SUBSTRATEoutput$regionData)){
  plot_rr_sf(regionMap, SUBSTRATEoutput$regionData, substrate_rr$attribute)
}
```

```{r SUBSTRATE-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(substrate_rr, "EN"), 'Map showing substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region within the search area (red outline). Data were obtained from @OpenData_substrate.')}
if(!is.null(SUBSTRATEoutput$studyData)){
  plot_rr_sf(areaMap, SUBSTRATEoutput$mapData, substrate_rr$attribute)
}
```
