---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r nitroLoad-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r nitroLoad-load-common-ha, child = here::here("reports/sections/commonSections/commonHA.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { 
  # load in generic data, e.g.functions, study area, and base maps into the 
  # environment, when knitting, these will be loaded through the child rmd.
  lapply(list.files(here::here("app/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment())
}
```

### **Estimates of anthropogenic nitrogen loading and eutrophication indicators for the Bay of Fundy and Scotian Shelf** {#nitroLoad-section}

```{r nitroLoad-load, include=FALSE}
# load in section specific data
load_rdata(c("nitroLoad_rr"), regionStr, env = environment())

```

```{r nitroLoad-meta, results='asis'}
# metadata blurb at start of each section
write_meta(totalNitroLoad_rr, "EN")
```


Dataset description from the Open Data record [@OpenData_nitroLoad; For the full methods see @nitroLoad_pub]:
```{r nitroLoad-text, results='asis'}
writeLines(noquote(totalNitroLoad_rr$text$en))

```


##### *Area-specific nitrogen load results*
```{r nitroLoad-results, include=FALSE, cache=FALSE}
# clip the data to the Study and Map areas:
totalOutputList <- master_intersect(totalNitroLoad_rr$data_sf, mapDataList, getRegion = TRUE)
deltaOutputList <- master_intersect(deltaNitroLoad_rr$data_sf, mapDataList, getRegion = TRUE)

# summary intro table
introResult <- !is.null(totalOutputList$studyData) | !is.null(deltaOutputList$studyData)
summaryIntroTable <- add_row_to_intro_summary(summaryIntroTable, name="[Nitrogen Loading](#nitroLoad-section)", result=introResult)


```


```{r nitroLoad-haTable, echo=FALSE, results='asis'}
if (!is.null(totalOutputList$studyData)) {
  rrEnv$haClassTable$`Nitrogen Loading` <- list("Coastal" = TRUE, 
                                            "Offshore" = TRUE, 
                                            "Shoreline" = TRUE)
}
```

```{r nitroLoad-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
nitroLoadReport <- if (is.null(totalOutputList$studyData) & is.null(deltaOutputList$studyData)) {
  "* There are no relevant nitrogen load records for this search area."
} else {
  "* There are relevant nitrogen load records for this search area."
}
writeLines(noquote(nitroLoadReport))
```

```{r totalNitroLoad-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(totalNitroLoad_rr, "EN"), 'Map of total nitrogen load (kg N/yr) from point and non-point source inputs (wastewater, atmospheric deposition, land use, fertilizer applications, and regional industries) within coastal watersheds (outlined in black) in the Scotian Shelf bioregion. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Dashed grey lines indicate international boundaries. Data were obtained from @OpenData_nitroLoad. For a full description of the methods see @nitroLoad_pub.')}
if (!is.null(totalOutputList$studyData)) {
    plot(plot_rr_sf(regionMap, totalOutputList$regionData, 
                    attribute=totalNitroLoad_rr$attribute, 
                    legendName="Nitrogen Load (kg/yr)", 
                    continuousAttr=TRUE))
}
```
 
```{r totalNitroLoad-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(totalNitroLoad_rr, "EN"), 'Map of total nitrogen load (kg N/yr) from point and non-point source inputs (wastewater, atmospheric deposition, land use, fertilizer applications, and regional industries) within coastal watersheds (outlined in black) in the search area (red outline). Data were obtained from @OpenData_nitroLoad. For a full description of the methods see @nitroLoad_pub.')}
if (!is.null(totalOutputList$studyData)) {
    totalRegionMax <- max(totalOutputList$regionData[[totalNitroLoad_rr$attribute]])
    totalRegionMin <- min(totalOutputList$regionData[[totalNitroLoad_rr$attribute]])
    plot(plot_rr_sf(areaMap, totalOutputList$mapData, 
                    attribute=totalNitroLoad_rr$attribute, 
                    legendName="Nitrogen Load (kg/yr)", 
                    continuousAttr=TRUE, 
                    minScale=totalRegionMin, maxScale=totalRegionMax))

    }
```

```{r deltaNitroLoad-region-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(deltaNitroLoad_rr, "EN"), 'Map of the mean ratio between the total nitrogen embayment loading rate and the sum of the rates of tidal exchange and freshwater recharge, observed within the Scotian Shelf bioregion. The search area is shown as a red outline, and a more detailed view is shown in the figure below, if relevant data are present. Dashed grey lines indicate international boundaries. Data were obtained from @OpenData_nitroLoad. For a full description of the methods see @nitroLoad_pub.')}
if (!is.null(deltaOutputList$studyData)) {
    plot(plot_rr_sf(regionMap, deltaOutputList$regionData, 
                    attribute=deltaNitroLoad_rr$attribute, 
                    legendName="Ratio", 
                    continuousAttr=TRUE))
}
```


```{r deltaNitroLoad-area-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(deltaNitroLoad_rr, "EN"), 'Map of the mean ratio between the total nitrogen embayment loading rate and the sum of the rates of tidal exchange and freshwater recharge, observed in the search area (red outline). Data were obtained from @OpenData_nitroLoad. For a full description of the methods see @nitroLoad_pub.')}
if (!is.null(deltaOutputList$studyData)) {
    deltaRegionMax <- max(deltaOutputList$regionData[[deltaNitroLoad_rr$attribute]])
    deltaRegionMin <- min(deltaOutputList$regionData[[deltaNitroLoad_rr$attribute]])
    plot(plot_rr_sf(areaMap, deltaOutputList$mapData, 
                    attribute=deltaNitroLoad_rr$attribute, 
                    legendName="Ratio", 
                    continuousAttr=TRUE, 
                    minScale=deltaRegionMin, maxScale=deltaRegionMax))

    }
```


