---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---

```{r {{imSection}}-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```

```{r eval=FALSE}
if (FALSE) { 
  # load in generic data, e.g.functions, study area, and base maps into the 
  # environment, when knitting, these will be loaded through the child rmd.
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson"))
  intro_setup(studyArea, env = environment())
}
```

```{r {{imSection}}-load, include=FALSE}
# load in section specific data
load_rdata(c("{{imSection}}_rr"), regionStr, env = environment())
imSection_rr <- get("{{imSection}}_rr")

```

#### *`r imSection_rr$datasetName` * {#{{imSection}}-section}

```{r {{imSection}}-meta, results='asis'}
# metadata blurb at start of each section
write_meta(imSection_rr, "EN")
```

```{r {{imSection}}-text, results='asis'}
# metadata blurb at start of each section
  writeLines(imSection_rr$text$en, sep="  \n")
```

```{r {{imSection}}-results, include=FALSE, cache=FALSE}
# clip the data to the Study and Map areas:
outputList <- master_intersect(imSection_rr$data_sf, mapDataList, getRegion = TRUE)

outputTable <- isle_madame_table(outputList$studyData, cols={{ cols }}, colnames = {{ colnames }})

```

```{r {{imSection}}-check, echo=FALSE, results='asis',}
# Check if there is any data in the study area
outputReport <- if (is.null(outputList$studyData)) {
  paste("* There are no relevant", imSection_rr$datasetName, "records for this search area.")
} else {
  paste("* There are relevant", imSection_rr$datasetName, "records for this search area.")
}
writeLines(noquote(outputReport))
```

```{r {{imSection}}-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(imSection_rr, "EN"), 'Map showing the search area defined by the user (red outline) used to query information from', imSection_rr$datasetName, 'records .')}

if (!is.null(outputList$studyData)) {
  # common plotting function:
  if (imSection_rr$attribute %in% names(outputList$mapData)){
     plotData <- outputList$mapData %>% dplyr::filter(sf::st_drop_geometry(outputList$mapData[imSection_rr$attribute]) != "Verify with original record")
    if (nrow(plotData) > 0) {
      plot_rr_sf(areaMap, plotData, attribute = 
               imSection_rr$attribute)    
    }
  }
}
```

```{r {{imSection}}-table}
if (!is.null(outputTable)) {
    knitr::kable(outputTable, align = "l", caption = paste("\\label{tab:{{imSection}}Table}", write_caption_blurb(imSection_rr, "EN"),  imSection_rr$datasetName,  "records contained within the search area. The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. </b>"), booktabs = T, escape = F, linesep = "") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}

```
