
---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r pasBay-load-common, child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
```  

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())
}
```

### **Passamaquoddy Bay Biodiversity Trawls (PBBT)**  {#pasBay-section}

```{r pasBay-load, include=FALSE}
load_rdata(c("pasBay_rr"), "MAR", env = environment())
```

```{r pasBay-meta, results='asis'}
write_meta(pasBay_rr, "EN")
```

Dataset description from the Open Data record [@OpenData_pasBay]:
```{r pasBay-text, results='asis'}
writeLines(noquote(pasBay_rr$text$en))
```

##### *Area-Specific Search Results for the Passamaquoddy Bay Biodiversity Trawls*

```{r pasBay-results, include=FALSE, cache=FALSE}
pasBayClipped <- master_intersect(pasBay_rr$data_sf, mapDataList)

tableList <- create_sar_tables(pasBayClipped$studyData, listed_species)
pasBayAllTable <- tableList$allSpecies
pasBaySarTable <- tableList$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[PBBT](#pasBay-section)", pasBaySarTable, "Common Name", "Common Name")

```

```{r pasBay-check, comment="", prompt=TRUE, echo=FALSE, results='asis'}
pasBayCheck <- if (!is.null(pasBayClipped$studyData)) {
    "* There are relevant records in the Passamaquoddy Bay Biodiversity Trawls for this search area."
  } else {
    "* There are no relevant records in the Passamaquoddy Bay Biodiversity Trawls for this search area. "
  }
writeLines(noquote(pasBayCheck))
```

```{r pasBay-plot, fig.height=7, fig.width=11, fig.cap=paste(write_caption_blurb(pasBay_rr, "EN"), 'Map of Passamaquoddy Bay Biodiversity Trawls within the search area (red outline). Blue lines indicate the location of each trawl sample. Data were obtained from @OpenData_pasBay')}

if (!is.null(pasBayClipped$studyData)) {
    plot_rr_sf(areaMap, pasBayClipped$mapData, lwd = 0.7, colour = "blue")
}
```
<br>
```{r pasBay-SAR-table}
if (!is.null(pasBayClipped$studyData)) {
  if (nrow(pasBaySarTable) > 0) {
    knitr::kable(pasBaySarTable, align="l", caption=paste("\\label{tab:pasBay_SAR_table}", write_caption_blurb(pasBay_rr, "EN"), "Passamaquoddy Bay Biodiversity Trawl observation records of species contained within the search area (red outline) and listed by the Species At Risk Act (SARA) and/or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. </b>"), booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
  }
}
```
<br>
```{r pasBay-all-table}
if (!is.null(pasBayClipped$studyData)) {
knitr::kable(pasBayAllTable, align="l", caption=paste("\\label{tab:pasBay_all_table}", write_caption_blurb(pasBay_rr, "EN"), "Passamaquoddy Bay Biodiversity Trawl observation records of all species contained within the search area, summarized by species or species group. The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. </b>"), booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```
