---
output:
  bookdown::html_document2:
    number_sections: FALSE
    theme: paper
bibliography: '`r here::here("app/data/mybiblio.bib")`'
---
```{r child = here::here("reports/sections/commonSections/commonIntro.Rmd")}
``` 

```{r eval=FALSE}
if (FALSE) { #load in data:
  lapply(list.files(here::here("reports/R"), pattern = ".[Rr]$", full.names = TRUE), source)
  studyArea <- sf::st_read(here::here("app/output/geoms_slc.geojson")) 
  intro_setup(studyArea, env = environment())  
}
```

### **Chalut de biodiversité de la baie de Passamaquoddy (CBBP)**  {#pasBay-section}

```{r pasBay-load, include=FALSE}
load_rdata(c("pasBay_rr"), "MAR", env = environment())
```

```{r pasBay-meta, results='asis'}
write_meta(pasBay_rr, "FR")
```

Description de l’ensemble de données (tirée du dossier des données ouvertes) [@OpenData_pasBay]:
```{r pasBay-text, results='asis'}
writeLines(noquote(pasBay_rr$text$fr))
```

#### ***Résultats de la Chalut de biodiversité de la baie de Passamaquoddy, par zone***


```{r pasBay-results, include=FALSE, cache=FALSE}
pasBayClipped <- master_intersect(pasBay_rr$data_sf, mapDataList)

tableList <- create_sar_tables(pasBayClipped$studyData, listed_species)
pasBayAllTable <- tableList$allSpecies
pasBaySarTable <- tableList$sarData
summarySarTable <- add_col_to_sar_summary(summarySarTable, "[CBBP](#pasBay-section)", pasBaySarTable, "Common Name", "Common Name")

```

```{r pasBay-check, comment="", prompt=TRUE, echo=FALSE, results='asis'}
pasBayCheck <- if (!is.null(pasBayClipped$studyData)) {
    "*  Il existe des registres pertinents dans le chalut de biodiversité de la baie de Passamaquoddy pour cette zone de recherche."
  } else {
    "*  Il n'existe aucune registre pertinent dans le chalut de biodiversité de la baie de Passamaquoddy pour cette zone de recherche. "
  }
writeLines(noquote(pasBayCheck))
```

```{r pasBay-plot, fig.height=7, fig.width=11, fig.cap= 'Quality Tier: High. Security level: None. Map showing the search area defined by the user (red outline) used to query information from the Passamaquoddy Bay Biodiversity Trawls.  Blue lines indicate the location of each trawl sample.'}

if (!is.null(pasBayClipped$studyData)) {
    plot_rr_sf(areaMap, pasBayClipped$mapData, lwd = 0.7, colour = "blue")
}
```
<br>
```{r pasBay-SAR-table}
if (!is.null(pasBayClipped$studyData)) {
  if (nrow(pasBaySarTable) > 0) {
    knitr::kable(pasBaySarTable, align="l", caption="\\label{tab:pasBay_SAR_table}Quality Tier: High. Security level: None. Passamaquoddy Bay Biodiversity Trawl observation records of species contained within the search area and listed by the Species At Risk Act (SARA), or assessed by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC). The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. </b>", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
  }
}
```
<br>
```{r pasBay-all-table}
if (!is.null(pasBayClipped$studyData)) {
knitr::kable(pasBayAllTable, align="l", caption="\\label{tab:pasBay_all_table}Quality Tier: High. Security level: none. Passamaquoddy Bay Biodiversity Trawl observation records of all species contained within the search area, summarized by species or species group. The absence of a species in this table should be interpreted as an absence of reporting, not necessarily as an absence of the species in the area. </b>", booktabs = T, escape = F, linesep="") %>% kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
}
```
