# This is a workflow to check for open data updates

name: Open Data Check
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        default: 'World'
        required: false
  schedule:
  - cron: "0 12 * * *"

jobs:
  setup_renv_check:
    runs-on: ubuntu-latest
    
    env:
      # Root path used by renv and cached
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
    
      name: nuke Rprofile
        run: rm .Rprofile
    
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-renv@v1
      with:
        cache-version: 2
      
      - name: Run opendata check
        run: source(here::here("dataprocessing/openDataGitScript.R")) 
        shell: Rscript {0}
