# This is a workflow to check for open data updates

name: Open Data Check
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        default: 'World'
        required: false
  schedule:
  - cron: "0 0 10 * *"

jobs:
  setup_renv_check:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
    
      - name: nuke Rprofile
        run: rm .Rprofile
    
      - uses: r-lib/actions/setup-r@v1
      
      - name: Run opendata check
        run: |
          install.packages("ckanr", "here", "dplyr")
          source(here::here("dataprocessing/openDataGitScript.R"))
        shell: Rscript {0}