# This is a workflow to check for open data updates

name: Open Data Check
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        default: 'World'
        required: false
  schedule:
  # run at 10am every wednesday
  - cron: "0 10 1 1 *"

jobs:
  open_data_check:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
    
      - uses: r-lib/actions/setup-r@v2
      
      - name: Fix ubuntu packages
        run: |
          sudo apt install libcurl4-openssl-dev 
      
      - name: Install R packages
        run: |
          install.packages(c("ckanr", "here"), quiet=TRUE)
        shell: Rscript {0}  
        
      - name: Run Script
        run: |
          source(here::here("reports/dataprocessing/openDataGitScript.R"))
        shell: Rscript {0}
