# This is a workflow to check for open data updates

name: Open Data Check
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        default: 'World'
        required: false
  schedule:
  - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-production:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          cache-version: 2
          
          
      - name: Send greeting
        run: ls
          


        
      - name: Send end  greeting
        run: echo "Goodbye World"
